name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Validate blog post name
        run: |
          TOTAL_POST_COUNT=$(ls -l posts/**/*.md | wc -l)
          VALIDATED_POST_COUNT=$(ls posts/**/*.md | xargs -n1 basename | grep -cE '^[0-9]{8,}-')
          if [ $TOTAL_POST_COUNT != $VALIDATED_POST_COUNT ]; then
            INVALID_POST=$(ls posts/**/*.md | xargs -n1 basename | grep -vE '^[0-9]{8,}-')
            echo "Post names are not followed by name format: yyyyMMdd-{ANY_STRING}"
            echo "====Invalid post names===="
            echo "$INVALID_POST"
            echo "=========================="
            exit 1
          fi
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Execute unittest
        run: bun test
