name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup and load cache if it exists
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Validate blog post name
        run: |
          TOTAL_POST_COUNT=$(ls -l posts/**/*.md | wc -l)
          VALIDATED_POST_COUNT=$(ls posts/**/*.md | xargs -n1 basename | grep -cE '^[0-9]{8,}-')
          if [ $TOTAL_POST_COUNT != $VALIDATED_POST_COUNT ]; then
            echo "Some blog post names are not followed by name format: yyyyMMdd-{ANY_STRING}"
            echo "TOTAL_POST_COUNT=$TOTAL_POST_COUNT VALIDATED_POST_COUNT=$VALIDATED_POST_COUNT"
            exit 1
          fi
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Execute unittest
        run: yarn test
