name: CI
on: [push]

jobs:
  build:
    name: Build applications and execute unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup and load cache if it exists
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Execute unittest
        run: yarn test