name: Release note generator
on:
  push:
    branches:
      - main

jobs:
  release-note-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "${{ github.base_ref }}"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.base_ref }}
      - name: Checkout "${{ github.head_ref }}"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      - name: Get release version
        run: |
          echo "VERSION=$(grep '"version":' package.json | awk '{print $2}' | sed -e 's/\"//g; s/,//g')" >> $GITHUB_ENV
      - name: Generate release notes
        run: |
          gh release create "v${{ env.VERSION }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
