name: Release version checker
on: 
  pull_request:
    branches: 
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check version updates
        run: |
          git diff -- package.json | grep '\"version\": '
          diff=$(git diff -- package.json | grep '\"version\": ' | wc -l)
          if [ $diff != 0]; then
            exit 1
          else
            exit 0
          fi