name: Release version checker
on:
  pull_request:
    branches:
      - main

jobs:
  release-version-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "${{ github.base_ref }}"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.base_ref }}
      - name: Checkout "${{ github.head_ref }}"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      - name: Check version updates
        shell: bash
        run: |
          git diff origin/${{ github.base_ref }} -- package.json | grep '\"version\": '
          diff=`git diff origin/${{ github.base_ref }} -- package.json | grep '\"version\": ' | wc -l`
          if [ $diff != 0 ]; then
            exit 0
          else
            exit 1
          fi
